version: '2'
services:
  roshambo-client:
    container_name: roshambo-client
    build:
      context: .
      dockerfile: ops/docker/Dockerfile
      args:
        - NODE_ENV=development
    image: roshambo-client
    ports:
      - '3000:3000'
    volumes:
      - ./src:/opt/app/src:cached
